### ISSUE TITLE
Tambahkan sedikit informasi 

### ISSUE THREAD

**Issue by mohamad-supangat** [mnabila/gruvboy.nvim#1]
Mungkin bisa sedikit tambahan tutorial instalasi

karna itu sangat berguna bagi pengguna baru seperti saya tentunya 

Terimakasih telah membuat plugin vim ini

**Comment by mnabila** [comment]
bisa bisa, nanti saya tambahkan bagaimana instalasinya untuk pengguna neovim

**Comment by mnabila** [comment]
sudah ditambakan ya kak 
e309a1f
